---
apiVersion: v1
kind: Namespace
metadata:
  name: nginx
  annotations:
    com.illumio.pairing_key: <replace with your pairing key>
---
apiVersion: v1
kind: Service
metadata:
  name: nginx
  namespace: nginx
  labels:
    application: nginx
    function: frontend
  annotations:
    com.illumio.role: web
spec:
  # type: LoadBalancer
  # ports:
  # - port: 80
  # selector:
  #   application: nginx
  #   function: frontend  
  type: NodePort
  ports:
  - port: 80
    nodePort: 30011
  selector:
   application: nginx
   function: frontend
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx
  namespace: nginx
  labels:
    application: nginx
    function: frontend
  annotations:
    com.illumio.role: web
spec:
  replicas: 3
  selector:
    matchLabels:
      application: nginx
      function: frontend
  template:
    metadata:
      labels:
        application: nginx
        function: frontend
    spec:
      affinity:
        nodeAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            nodeSelectorTerms:
            - matchExpressions:
              - key: kubernetes.io/arch
                operator: In
                values:
                - amd64
                - arm64
      containers:
      - name: nginx
        image: public.ecr.aws/nginx/nginx:1.23
        ports:
        - name: http
          containerPort: 80
        imagePullPolicy: IfNotPresent
      nodeSelector:
        kubernetes.io/os: linux

