kind: LabelMap
apiVersion: ic4k.illumio.com/v1alpha1
metadata:
  name: default
workloadLabelMap:
  - allowCreate: true
    fromKey: application
    toKey: app
    valuesMap:
      - from: nginx
        to: updated-nginx
  - allowCreate: true
    fromKey: app.kubernetes.io/name
    toKey: app
  - allowCreate: true
    fromKey: org
    toKey: env
    valuesMap:
      - from: empire
        to: empire
      - from: alliance
        to: alliance
  # - allowCreate: false
  #   fromKey: function
  #   toKey: role