kind: LabelMap
apiVersion: ic4k.illumio.com/v1alpha1
metadata:
  name: default
workloadLabelMap:
  - allowCreate: true
    fromKey: application
    toKey: app
    valuesMap:
      - from: nginx
        to: newnginx
  - allowCreate: true
    fromKey: app.kubernetes.io/name
    toKey: app
    valuesMap:
      - from: deathstar
        to: newdeathstar
  - allowCreate: true
    fromKey: org
    toKey: env
  - allowCreate: false
    fromKey: function
    toKey: role